version: "3.8"
services:
  db:
    container_name: mgdb_prod
    image: mysql:8.0.29
    environment:
      MYSQL_DATABASE: prod
      MYSQL_ROOT_PASSWORD: password
  backend:
    container_name: mgdb_backend
    build: ./backend
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db
  frontend:
    container_name: mgdb_frontend
    build: ./frontend
    ports:
      - 80:3000
    depends_on:
      - db
